import * as FUIR from '@fluentui/react';
import { withGlobalState } from '@jsdt/tuneable';
import TuneableProvider from './provider';
import TuneableAlert from './alert';
import TuneableIcon from './icon';

export const Provider = withGlobalState(TuneableProvider);
export const Accordion = withGlobalState(FUIR.Accordion);
export const Alert = withGlobalState(TuneableAlert);
export const Animation = withGlobalState(FUIR.Animation);
export const Avatar = withGlobalState(FUIR.Avatar);
export const Button = withGlobalState(FUIR.Button);
export const ButtonGroup = withGlobalState(FUIR.ButtonGroup);
export const Chat = withGlobalState(FUIR.Chat);
export const ChatItem = withGlobalState(FUIR.ChatItem);
export const ChatMessage = withGlobalState(FUIR.ChatMessage);
export const Dialog = withGlobalState(FUIR.Dialog);
export const Divider = withGlobalState(FUIR.Divider);
export const Dropdown = withGlobalState(FUIR.Dropdown);
export const DropdownItem = withGlobalState(FUIR.DropdownItem);
// export const DropdownLabel = withGlobalState(FUIR.DropdownLabel);
export const DropdownSearchInput = withGlobalState(FUIR.DropdownSearchInput);
export const FocusZoneMode = withGlobalState(FUIR.FocusZoneMode);
export const Form = withGlobalState(FUIR.Form);
export const FormField = withGlobalState(FUIR.FormField);
export const Grid = withGlobalState(FUIR.Grid);
export const Header = withGlobalState(FUIR.Header);
export const HeaderDescription = withGlobalState(FUIR.HeaderDescription);
export const Icon = withGlobalState(TuneableIcon);
export const Image = withGlobalState(FUIR.Image);
export const Input = withGlobalState(FUIR.Input);
export const ItemLayout = withGlobalState(FUIR.ItemLayout);
export const Label = withGlobalState(FUIR.Label);
export const Layout = withGlobalState(FUIR.Layout);
export const List = withGlobalState(FUIR.List);
export const ListItem = withGlobalState(FUIR.ListItem);
export const Menu = withGlobalState(FUIR.Menu);
export const MenuItem = withGlobalState(FUIR.MenuItem);
export const Popup = withGlobalState(FUIR.Popup);
export const PopupContent = withGlobalState(FUIR.PopupContent);
export const Portal = withGlobalState(FUIR.Portal);
export const ProviderConsumer = withGlobalState(FUIR.ProviderConsumer);
export const RadioGroup = withGlobalState(FUIR.RadioGroup);
export const RadioGroupItem = withGlobalState(FUIR.RadioGroupItem);
export const Ref = withGlobalState(FUIR.Ref);
export const Segment = withGlobalState(FUIR.Segment);
export const Status = withGlobalState(FUIR.Status);
export const Text = withGlobalState(FUIR.Text);
export const Tree = withGlobalState(FUIR.Tree);
